### ISSUE TITLE
Finish unit tests for ActionSpaceBase

### ISSUE THREAD

**Issue by CinquilCinquil** [UFRN-URNAI/urnai-tools#105]
The [ActionSpaceBase](https://github.com/UFRN-URNAI/urnai-tools/blob/v2/urnai/actions/action_space_base.py) class is missing a test for the `get_actions_id` method.

**Comment by RickFqt** [comment]
Are we still going to use the `ActionBase` and `ChainOfActionBase` classes? I recall from some meetings ago that if we were to use `ActionBase` for example, we would have to create one subclass for each of the actions we would want to use (and that would be a lot of sublcasses). Then, at least for StarCraft2, we created [`SC2Action`](https://github.com/UFRN-URNAI/urnai-tools/blob/v2/urnai/sc2/actions/sc2_action.py) to avoid this problem. Is that right?

If so, in `ActionSpaceBase`, I think we should replace `ActionBase` with `int`, that would represent the actions' indices. Also, we would have to change the implementation of `get_actions_id` method, since it relies on `ActionBase` too. What do you think?

**Comment by CinquilCinquil** [comment]
I recall we had to create [SC2Action](https://github.com/UFRN-URNAI/urnai-tools/blob/v2/urnai/sc2/actions/sc2_action.py) for StarCraft2, but i don't remember the conclusions we had for the Action classes in general in URNAI. It doesn't seem correct to me to modify the entire library, abandoning `ActionBase` and `ChainOfActionBase`, just to fit the sc2 environment.

I think this is a good topic to discuss in the next meeting.
