### ISSUE TITLE
Choose testing framework

### ISSUE THREAD

**Issue by alvarofpp** [UFRN-URNAI/urnai-tools#22]

**Comment by marcocspc** [comment]
Most used test libraries/frameworks:
- PyTest
- UnitTest

I liked **UnitTest**:
Because it is part of Python's standad library;
Define directory and naming standards, which I particularly like;
It is one of the most used frameworks for Python, always showing as one of the first choices in lists like these:

- https://www.softwaretestinghelp.com/python-testing-frameworks/
- https://blog.testproject.io/2020/10/27/top-python-testing-frameworks/
- https://www.zenesys.com/blog/unit-testing-frameworks-in-python
- https://docs.python-guide.org/writing/tests/

Also has a tutorial from [Socratica](https://coverage.readthedocs.io/en/6.3/).


And is compatible with [Coverage](https://coverage.readthedocs.io/en/6.3/), which is a tool to discover test coverage in Python. This one will be very useful for us.

**Comment by alvarofpp** [comment]
@marcocspc PyTest is above UnitTest in two of the top three lists you have placed.

I really like the style of creating tests using classes, but PyTest has some other benefits when compared to UniTest, like: UnitTest cannot run tests in parallel, but PyTest can. Also PyTest is compatible with Coverage too.

----------

Some packages and their respective testing frameworks:

**UnitTest**:

- [tensorflow](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/python/keras/keras_parameterized_test.py#L17)

**PyTest**:

- [pandas](https://github.com/pandas-dev/pandas/blob/2dd75ca5e04a18db9d79d9bed01726b40b6268e9/requirements-dev.txt#L44)
- [fklearn](https://github.com/nubank/fklearn/blob/master/pytest.ini)
- [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/1e4ac040eef6bc8c43c77122bbfdd5d83cb8365a/sklearn/utils/tests/test_validation.py#L12)

**Comment by lpdcalves** [comment]
I've used both UnitTest and PyTest on urnai previously. I've personally found PyTest to be more flexible and easier to use, allowing me to do not only unit tests but also more general integration tests quite easily, by just prepending "test_" to a funcion name.

**Comment by alvarofpp** [comment]
- **Pytest**: 2 votes.
- Unittest: 1 vote.
